version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      size: medium
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    steps:
      - checkout
      - run: cd src ; if ($?) { dotnet restore }
      - run: cd src ; if ($?) { dotnet build }
      - run: cd src ; if ($?) { dotnet test }
